import type { NextPage } from "next";
import Head from "next/head";
import { useCounter } from "hooks/useCounter";
import styles from "styles/Home.module.css";

const Home: NextPage = () => {
  const { count, increment, decrement, reset } = useCounter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Count App by Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{count}</h1>

        <div className={styles.grid}>
          <button className={styles.button} onClick={increment}>
            Plus
          </button>
          <button className={styles.button} onClick={decrement}>
            Minus
          </button>
          <button
            className={`${styles.button} ${styles.destructive}`}
            onClick={reset}
          >
            Reset
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
