import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [count, setCount] = useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Count App by Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{count}</h1>

        <div className={styles.grid}>
          <button
            className={styles.button}
            onClick={() => setCount(() => count + 1)}
          >
            Plus
          </button>
          <button
            className={styles.button}
            onClick={() => setCount(() => count - 1)}
          >
            Minus
          </button>
          <button
            className={`${styles.button} ${styles.destructive}`}
            onClick={() => setCount(0)}
          >
            Reset
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
